name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    container: rgilton/sr-kitbook-builder:58bdd329

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: setup-env
        run: pipenv install --deploy --dev

      - name: Build it all
        run: pipenv run build

      - name: Lint YAML
        run: pipenv run lint-yaml
